### PR TITLE
Add MFI/PS4/XboxOne controller support

### PR DESCRIPTION
**Pull request by WeedyWeedSmoker**
thanks to @Ichicoro's great patch (https://gist.github.com/Ichicoro/65eebe3644c327a033091fa1168fc6d5)

### CODE REVIEW

**Comment by WeedyWeedSmoker** [comment]
BTW, I'm not a coder or developer AT ALL! This code is probably not correctly indented, I just used some common sense and testing to achieve the expected results… ;-)

Thanks @OatmealDome for this great project, I really love it!

**Comment by OatmealDome** [comment]
Thanks for the contribution, but a cleaner implementation (using code that [isn't copied direct from a tutorial](https://medium.com/@samdubois18/adding-controller-support-to-your-ios-app-a9b8308ce0b4) and that will support rebinds) will be added later.

**Comment by WeedyWeedSmoker** [comment]
@OatmealDome Wow! I didn't know this was not @Ichicoro's original code… Anyway that's GREAT news!

Love to hear that…

**Comment by Ichicoro** [comment]
@OatmealDome I did use that tutorial but I didn't copy paste, I rewrote some parts too. Either way, mine was a quick way to implement it so I could play WW :) 

I don't understand if that was meant to be a negative thing... 😅

**Comment by WeedyWeedSmoker** [comment]
@Ichicoro It's not a negative thing at all, my implementation of your code is tweaked to add Wiimote and Nunchuk support, and your code allows me to play Wii/GC games with a controller, which is great IMO!

The thing is that seems to only work on iOS 13, correct? (I'm not sure as I don't have supported iOS 12 devices anymore…) And the select button I couldn't get to work on my PS4 controller… Could you shed some light on that?

Anyway, thanks!

**Pull request closed without merging**
